"""
scripts/05_run_audit.py

Runs the full pre-registered audit BEFORE the core LODO transfer
experiment (scripts/04_run_lodo_experiment.py) is allowed to be reported
as a result. This ordering is deliberate: the construct-floor numbers and
null-alignment numbers are the yardstick the main experiment's headline
transfer score has to be read against, so they need to exist first.

Usage:
    python scripts/05_run_audit.py [--seed 42] [--out results/audit_report.md]

# VERIFY: run this from the repo root (eeg-crossdomain/) so the relative
# import of src/ resolves. On Brev, once real Stage-2 caches exist, no
# code here changes -- only load_harmonized_features() in
# src/construct_floor.py needs to point at the real cache instead of the
# synthetic generator.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from construct_floor import run_all_construct_floors          # noqa: E402
from null_alignment import run_null_alignment_audit            # noqa: E402


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--out", type=str, default="results/audit_report.md")
    args = parser.parse_args()

    print("=" * 70)
    print("STEP 1 / 2 -- Construct-floor check")
    print("=" * 70)
    floor_results = run_all_construct_floors(seed=args.seed)

    print()
    print("=" * 70)
    print("STEP 2 / 2 -- Null-alignment audit")
    print("=" * 70)
    alignment_results = run_null_alignment_audit(seed=args.seed)

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        f.write("# Cross-domain audit report\n\n")
        f.write(
            "Generated by scripts/05_run_audit.py. Figures below are from "
            "SYNTHETIC placeholder data until real Stage-2 caches are wired "
            "in on Brev (see # VERIFY markers in src/construct_floor.py and "
            "src/null_alignment.py).\n\n"
        )
        f.write("## 1. Construct floor (per dataset, generic-feature linear probe)\n\n")
        f.write("| Dataset | Floor AUC | 95% CI |\n|---|---|---|\n")
        for r in floor_results:
            f.write(f"| {r['dataset']} | {r['mean_auc']:.3f} | [{r['ci_lo']:.3f}, {r['ci_hi']:.3f}] |\n")
        f.write("\n## 2. Null-alignment audit (Holm-corrected within family)\n\n")
        f.write("| Comparison | Mean Δ AUC | 95% CI | p_raw | p_holm | n |\n|---|---|---|---|---|---|\n")
        for s in alignment_results:
            f.write(
                f"| {s['label']} | {s['mean_diff']:.4f} | "
                f"[{s['ci_lo']:.3f}, {s['ci_hi']:.3f}] | {s['p_raw']:.3f} | "
                f"{s['p_holm']:.3f} | {s['n_pairs']} |\n"
            )
        f.write(
            "\n## Decision rule\n\n"
            "The main LODO transfer result (scripts/04_run_lodo_experiment.py) "
            "is reportable as evidence of real cross-paradigm structure only if:\n"
            "1. `real_alignment` ROC-AUC on the held-out dataset exceeds that "
            "dataset's own construct floor (Section 1), AND\n"
            "2. `real_alignment` significantly beats all three null "
            "conditions after Holm correction (Section 2).\n\n"
            "If (1) fails: transfer has not exceeded what the target "
            "dataset's own generic features already give away.\n"
            "If (2) fails: the alignment step is not demonstrably using "
            "the true domain gap or the true target geometry, however "
            "large its raw effect looks.\n"
        )

    print(f"\nAudit report written to {out_path}")


if __name__ == "__main__":
    main()
